#ifndef MESSAGERECEIVEDENUM_H
#define MESSAGERECEIVEDENUM_H

enum class MessageReceivedType {
  TEXT_MESSAGE,
  CANVAS_MESSAGE,
  USER_JOINED,
  USER_LEFT,
  JOINED_ROOM,
  GET_ROOMS,
  NEW_HOST,
  GAME_START,
  GAME_OVER,
  ERROR
};

#endif // MESSAGERECEIVEDENUM_H
