name: test_project

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs: 
  build_and_run_tests: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: "Install Qt"
        uses: jurplel/install-qt-action@v2
        
      - name: "Create test build dir"
        run: "mkdir build"
        work-directory: ./tests
        
      - name: "Build tests with qmake"
        run: "qmake .."
        work-directory: ./tests/build
        
      - name: "Build tests with make"
        run: make
        work-directory: ./tests/build
        
      - name: "Run tests"
        run: ./test
        work-directory: ./tests/build
        
      - name: Report
        run: "echo Tests passed!"
